import random
import sys
import time
def mengetik(s):
    for c in s + '\n':
        sys.stdout.write(c)
        sys.stdout.flush()
        time.sleep(random.random() * 0.01)
mengetik('ANAK KONTOLLL')
mengetik('ANAK KONTOLLL')
mengetik('ANAK KONTOLLL')
mengetik('ANAK KONTOLLL')
mengetik('ANAK KONTOLLL')
mengetik('ANAK KONTOLLL')
mengetik('ANAK KONTOLLL')
mengetik('ANAK KONTOLLL')
mengetik('ANAK KONTOLLL')
mengetik('ANAK KONTOLLL')
mengetik('ANAK KONTOLLL')
mengetik('ANAK KONTOLLL')
mengetik('ANAK KONTOLLL')
mengetik('ANAK KONTOLLL')
mengetik('ANAK KONTOLLL')
mengetik('ANAK KONTOLLL')
mengetik('ANAK KONTOLLL')
mengetik('ANAK KONTOLLL')
mengetik('ANAK KONTOLLL')
mengetik('ANAK KONTOLLL')
mengetik('ANAK KONTOLLL')
mengetik('ANAK KONTOLLL')
mengetik('ANAK KONTOLLL')
mengetik('ANAK KONTOLLL')
mengetik('ANAK KONTOLLL')
mengetik('ANAK KONTOLLL')
mengetik('ANAK KONTOLLL')
mengetik('ANAK KONTOLLL')
mengetik('ANAK KONTOLLL')
mengetik('ANAK KONTOLLL')
mengetik('ANAK KONTOLLL')
mengetik('ANAK KONTOLLL')
mengetik('ANAK KONTOLLL')
mengetik('ANAK KONTOLLL')
mengetik('ANAK KONTOLLL')
mengetik('ANAK KONTOLLL')
mengetik('ANAK KONTOLLL')
mengetik('ANAK KONTOLLL')
mengetik('ANAK KONTOLLL')
mengetik('ANAK KONTOLLL')
mengetik('ANAK KONTOLLL')
mengetik('ANAK KONTOLLL')
mengetik('ANAK KONTOLLL')
mengetik('ANAK KONTOLLL')
mengetik('ANAK KONTOLLL')
mengetik('ANAK KONTOLLL')
mengetik('ANAK KONTOLLL')
mengetik('ANAK KONTOLLL')
mengetik('ANAK KONTOLLL')
mengetik('ANAK KONTOLLL')
mengetik('ANAK KONTOLLL')
mengetik('ANAK KONTOLLL')
mengetik('ANAK KONTOLLL')
mengetik('ANAK KONTOLLL')
mengetik('ANAK KONTOLLL')
mengetik('ANAK KONTOLLL')
mengetik('ANAK KONTOLLL')
mengetik('ANAK KONTOLLL')
mengetik('ANAK KONTOLLL')
mengetik('ANAK KONTOLLL')
mengetik('ANAK KONTOLLL')
mengetik('ANAK KONTOLLL')
mengetik('ANAK KONTOLLL')
mengetik('ANAK KONTOLLL')
mengetik('ANAK KONTOLLL')
mengetik('ANAK KONTOLLL')
mengetik('ANAK KONTOLLL')
mengetik('ANAK KONTOLLL')
mengetik('ANAK KONTOLLL')
mengetik('ANAK KONTOLLL')
mengetik('ANAK KONTOLLL')
mengetik('ANAK KONTOLLL')
mengetik('ANAK KONTOLLL')
mengetik('ANAK KONTOLLL')
mengetik('ANAK KONTOLLL')
mengetik('ANAK KONTOLLL')
mengetik('ANAK KONTOLLL')
mengetik('ANAK KONTOLLL')
mengetik('ANAK KONTOLLL')
mengetik('ANAK KONTOLLL')
mengetik('ANAK KONTOLLL')
mengetik('ANAK KONTOLLL')
mengetik('ANAK KONTOLLL')
mengetik('ANAK KONTOLLL')
mengetik('ANAK KONTOLLL')
mengetik('ANAK KONTOLLL')
mengetik('ANAK KONTOLLL')
mengetik('ANAK KONTOLLL')
mengetik('ANAK KONTOLLL')
mengetik('ANAK KONTOLLL')

mengetik('ANAK KONTOLLL')
mengetik('ANAK KONTOLLL')
mengetik('ANAK KONTOLLL')
mengetik('ANAK KONTOLLL')
mengetik('ANAK KONTOLLL')
mengetik('ANAK KONTOLLL')
mengetik('ANAK KONTOLLL')
mengetik('ANAK KONTOLLL')
mengetik('ANAK KONTOLLL')
mengetik('ANAK KONTOLLL')


mengetik('MAMPUS LU ANJING')
mengetik('MAMPUS LU ANJING')
mengetik('MAMPUS LU ANJING')
mengetik('MAMPUS LU ANJING')
mengetik('MAMPUS LU ANJING')
mengetik('MAMPUS LU ANJING')
mengetik('MAMPUS LU ANJING')
mengetik('MAMPUS LU ANJING')
mengetik('MAMPUS LU ANJING')
mengetik('MAMPUS LU ANJING')
mengetik('MAMPUS LU ANJING')

mengetik('MAMPUS LU ANJING')
mengetik('MAMPUS LU ANJING')
mengetik('MAMPUS LU ANJING')
mengetik('MAMPUS LU ANJING')
mengetik('MAMPUS LU ANJING')
mengetik('MAMPUS LU ANJING')
mengetik('MAMPUS LU ANJING')
mengetik('MAMPUS LU ANJING')
mengetik('MAMPUS LU ANJING')
mengetik('MAMPUS LU ANJING')
mengetik('MAMPUS LU ANJING')
mengetik('MAMPUS LU ANJING')
mengetik('MAMPUS LU ANJING')
mengetik('MAMPUS LU ANJING')
mengetik('MAMPUS LU ANJING')
mengetik('MAMPUS LU ANJING')
mengetik('MAMPUS LU ANJING')
mengetik('MAMPUS LU ANJING')
mengetik('MAMPUS LU ANJING')
mengetik('MAMPUS LU ANJING')
mengetik('MAMPUS LU ANJING')
mengetik('MAMPUS LU ANJING')
mengetik('MAMPUS LU ANJING')
mengetik('MAMPUS LU ANJING')
mengetik('MAMPUS LU ANJING')
mengetik('MAMPUS LU ANJING')
mengetik('MAMPUS LU ANJING')
mengetik('MAMPUS LU ANJING')
mengetik('MAMPUS LU ANJING')
mengetik('MAMPUS LU ANJING')
mengetik('MAMPUS LU ANJING')
mengetik('MAMPUS LU ANJING')
mengetik('MAMPUS LU ANJING')

mengetik('MAMPUS LU ANJING')
mengetik('MAMPUS LU ANJING')
mengetik('MAMPUS LU ANJING')
mengetik('MAMPUS LU ANJING')
mengetik('MAMPUS LU ANJING')
mengetik('MAMPUS LU ANJING')
mengetik('MAMPUS LU ANJING')
mengetik('MAMPUS LU ANJING')
mengetik('MAMPUS LU ANJING')
mengetik('MAMPUS LU ANJING')
mengetik('MAMPUS LU ANJING')

mengetik('MAMPUS LU ANJING')
mengetik('MAMPUS LU ANJING')
mengetik('MAMPUS LU ANJING')
mengetik('MAMPUS LU ANJING')
mengetik('MAMPUS LU ANJING')
mengetik('MAMPUS LU ANJING')
mengetik('MAMPUS LU ANJING')
mengetik('MAMPUS LU ANJING')
mengetik('MAMPUS LU ANJING')
mengetik('MAMPUS LU ANJING')
mengetik('MAMPUS LU ANJING')
mengetik('MAMPUS LU ANJING')
mengetik('MAMPUS LU ANJING')
mengetik('MAMPUS LU ANJING')
mengetik('MAMPUS LU ANJING')
mengetik('MAMPUS LU ANJING')
mengetik('MAMPUS LU ANJING')
mengetik('MAMPUS LU ANJING')
mengetik('MAMPUS LU ANJING')
mengetik('MAMPUS LU ANJING')
mengetik('MAMPUS LU ANJING')
mengetik('MAMPUS LU ANJING')
mengetik('MAMPUS LU ANJING')
mengetik('MAMPUS LU ANJING')
mengetik('MAMPUS LU ANJING')
mengetik('MAMPUS LU ANJING')
mengetik('MAMPUS LU ANJING')
mengetik('MAMPUS LU ANJING')
mengetik('MAMPUS LU ANJING')
mengetik('MAMPUS LU ANJING')
mengetik('MAMPUS LU ANJING')
mengetik('MAMPUS LU ANJING')
mengetik('MAMPUS LU ANJING')

mengetik('MAMPUS LU ANJING')
mengetik('MAMPUS LU ANJING')
mengetik('MAMPUS LU ANJING')
mengetik('MAMPUS LU ANJING')
mengetik('MAMPUS LU ANJING')
mengetik('MAMPUS LU ANJING')
mengetik('MAMPUS LU ANJING')
mengetik('MAMPUS LU ANJING')
mengetik('MAMPUS LU ANJING')
mengetik('MAMPUS LU ANJING')
mengetik('MAMPUS LU ANJING')

mengetik('MAMPUS LU ANJING')
mengetik('MAMPUS LU ANJING')
mengetik('MAMPUS LU ANJING')
mengetik('MAMPUS LU ANJING')
mengetik('MAMPUS LU ANJING')
mengetik('MAMPUS LU ANJING')
mengetik('MAMPUS LU ANJING')
mengetik('MAMPUS LU ANJING')
mengetik('MAMPUS LU ANJING')
mengetik('MAMPUS LU ANJING')
mengetik('MAMPUS LU ANJING')
mengetik('MAMPUS LU ANJING')
mengetik('MAMPUS LU ANJING')
mengetik('MAMPUS LU ANJING')
mengetik('MAMPUS LU ANJING')
mengetik('MAMPUS LU ANJING')
mengetik('MAMPUS LU ANJING')
mengetik('MAMPUS LU ANJING')
mengetik('MAMPUS LU ANJING')
mengetik('MAMPUS LU ANJING')
mengetik('MAMPUS LU ANJING')
mengetik('MAMPUS LU ANJING')
mengetik('MAMPUS LU ANJING')
mengetik('MAMPUS LU ANJING')
mengetik('MAMPUS LU ANJING')
mengetik('MAMPUS LU ANJING')
mengetik('MAMPUS LU ANJING')
mengetik('MAMPUS LU ANJING')
mengetik('MAMPUS LU ANJING')
mengetik('MAMPUS LU ANJING')
mengetik('MAMPUS LU ANJING')
mengetik('MAMPUS LU ANJING')
mengetik('MAMPUS LU ANJING')
mengetik('MAMPUS LU ANJING')
mengetik('MAMPUS LU ANJING')
mengetik('MAMPUS LU ANJING')
mengetik('MAMPUS LU ANJING')
mengetik('MAMPUS LU ANJING')
mengetik('MAMPUS LU ANJING')
mengetik('MAMPUS LU ANJING')
mengetik('MAMPUS LU ANJING')
mengetik('MAMPUS LU ANJING')
mengetik('MAMPUS LU ANJING')
mengetik('MAMPUS LU ANJING')

mengetik('MAMPUS LU ANJING')
mengetik('MAMPUS LU ANJING')
mengetik('MAMPUS LU ANJING')
mengetik('MAMPUS LU ANJING')
mengetik('MAMPUS LU ANJING')
mengetik('MAMPUS LU ANJING')
mengetik('MAMPUS LU ANJING')
mengetik('MAMPUS LU ANJING')
mengetik('MAMPUS LU ANJING')
mengetik('MAMPUS LU ANJING')
mengetik('MAMPUS LU ANJING')
mengetik('MAMPUS LU ANJING')
mengetik('MAMPUS LU ANJING')
mengetik('MAMPUS LU ANJING')
mengetik('MAMPUS LU ANJING')
mengetik('MAMPUS LU ANJING')
mengetik('MAMPUS LU ANJING')
mengetik('MAMPUS LU ANJING')
mengetik('MAMPUS LU ANJING')
mengetik('MAMPUS LU ANJING')
mengetik('MAMPUS LU ANJING')
mengetik('MAMPUS LU ANJING')
mengetik('MAMPUS LU ANJING')
mengetik('MAMPUS LU ANJING')
mengetik('MAMPUS LU ANJING')
mengetik('MAMPUS LU ANJING')
mengetik('MAMPUS LU ANJING')
mengetik('MAMPUS LU ANJING')
mengetik('MAMPUS LU ANJING')
mengetik('MAMPUS LU ANJING')
mengetik('MAMPUS LU ANJING')
mengetik('MAMPUS LU ANJING')
mengetik('MAMPUS LU ANJING')
mengetik('MAMPUS LU ANJING')
mengetik('MAMPUS LU ANJING')
mengetik('MAMPUS LU ANJING')
mengetik('MAMPUS LU ANJING')
mengetik('MAMPUS LU ANJING')
mengetik('MAMPUS LU ANJING')
mengetik('MAMPUS LU ANJING')
mengetik('MAMPUS LU ANJING')
mengetik('MAMPUS LU ANJING')
mengetik('MAMPUS LU ANJING')
mengetik('MAMPUS LU ANJING')
mengetik('MAMPUS LU ANJING')
mengetik('MAMPUS LU ANJING')
mengetik('MAMPUS LU ANJING')
mengetik('MAMPUS LU ANJING')
mengetik('MAMPUS LU ANJING')
mengetik('MAMPUS LU ANJING')
mengetik('MAMPUS LU ANJING')
mengetik('MAMPUS LU ANJING')
mengetik('MAMPUS LU ANJING')
mengetik('MAMPUS LU ANJING')
mengetik('MAMPUS LU ANJING')
mengetik('MAMPUS LU ANJING')
mengetik('MAMPUS LU ANJING')
mengetik('MAMPUS LU ANJING')
mengetik('MAMPUS LU ANJING')
mengetik('MAMPUS LU ANJING')
mengetik('MAMPUS LU ANJING')
mengetik('MAMPUS LU ANJING')
mengetik('MAMPUS LU ANJING')
mengetik('MAMPUS LU ANJING')
mengetik('MAMPUS LU ANJING')
mengetik('MAMPUS LU ANJING')
mengetik('MAMPUS LU ANJING')
mengetik('MAMPUS LU ANJING')
mengetik('MAMPUS LU ANJING')
mengetik('MAMPUS LU ANJING')
mengetik('MAMPUS LU ANJING')
mengetik('MAMPUS LU ANJING')
mengetik('MAMPUS LU ANJING')
mengetik('MAMPUS LU ANJING')
mengetik('MAMPUS LU ANJING')
mengetik('MAMPUS LU ANJING')
mengetik('MAMPUS LU ANJING')
